'use strict';

const { buildTimeline } = require('./timeline');

// Produces a single self-contained HTML file (no external assets, no server)
// that renders a shareable view of one trace. "Send your slow trace to a
// teammate as one .html file."
function toShareableHtml(trace) {
  const report = buildTimeline(trace);
  const data = JSON.stringify(report).replace(/</g, '\\u003c');

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Trace ${escapeHtml(report.requestId || '')} · ${escapeHtml(report.method)} ${escapeHtml(report.path)}</title>
<style>
  *,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
  :root{--bg:#0f1117;--surface:#1a1d27;--surface2:#242836;--border:#2e3348;--text:#e1e4ed;--text2:#8b8fa7;--accent:#6c5ce7;--accent2:#a29bfe;--green:#00cec9;--red:#ff7675;--orange:#fdcb6e;--blue:#74b9ff}
  body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:var(--bg);color:var(--text);line-height:1.6;padding:24px}
  .wrap{max-width:1000px;margin:0 auto}
  h1{font-size:20px;margin-bottom:4px}
  .sub{color:var(--text2);font-size:13px;margin-bottom:20px;font-family:monospace}
  .meta{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px;margin-bottom:20px}
  .card{background:var(--surface);border:1px solid var(--border);border-radius:10px;padding:14px}
  .card .lbl{font-size:11px;text-transform:uppercase;letter-spacing:.5px;color:var(--text2)}
  .card .val{font-size:22px;font-weight:700}
  .warn{background:rgba(255,118,117,.12);border:1px solid var(--red);border-radius:8px;padding:10px 14px;margin-bottom:10px;color:var(--red);font-size:13px}
  .tl-row{display:flex;align-items:center;margin-bottom:6px;font-size:13px}
  .tl-label{width:200px;flex-shrink:0;text-align:right;padding-right:12px;color:var(--text2);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
  .tl-bar-wrap{flex:1;height:22px;background:var(--surface2);border-radius:4px;position:relative;overflow:hidden}
  .tl-bar{height:100%;border-radius:4px;position:absolute;top:0;display:flex;align-items:center;padding-left:6px;font-size:11px;font-weight:600;color:#fff;min-width:3px}
  .tl-dur{margin-left:8px;color:var(--text2);font-size:12px;width:70px;flex-shrink:0}
  .c0{background:linear-gradient(90deg,#6c5ce7,#a29bfe)}.c1{background:linear-gradient(90deg,#00cec9,#81ecec)}
  .c2{background:linear-gradient(90deg,#fd79a8,#e84393)}.c3{background:linear-gradient(90deg,#fdcb6e,#f39c12)}
  .c4{background:linear-gradient(90deg,#74b9ff,#0984e3)}.c5{background:linear-gradient(90deg,#55efc4,#00b894)}
  .err{outline:2px solid var(--red)}
  footer{margin-top:24px;color:var(--text2);font-size:12px}
  a{color:var(--accent2)}
</style>
</head>
<body>
<div class="wrap">
  <h1 id="title"></h1>
  <div class="sub" id="sub"></div>
  <div class="meta" id="meta"></div>
  <div id="warnings"></div>
  <div id="timeline"></div>
  <footer>Generated by <a href="https://github.com/beingmartinbmc/node-request-trace">node-request-trace</a> · self-contained snapshot</footer>
</div>
<script>
const R = ${data};
document.getElementById('title').textContent = R.method + ' ' + R.path + ' — ' + R.totalDuration + 'ms (' + R.status + ')';
document.getElementById('sub').textContent = R.requestId || '';
const s = R.summary;
const meta = [
  ['Duration', R.totalDuration + 'ms'],
  ['Steps', R.stepCount],
  ['Coverage', s.coveragePercent + '%'],
  ['Bottleneck', s.bottleneck ? (s.bottleneck.name + ' ' + s.bottleneck.duration + 'ms') : '—'],
  ['Errors', s.errorCount]
];
document.getElementById('meta').innerHTML = meta.map(m =>
  '<div class="card"><div class="lbl">' + m[0] + '</div><div class="val">' + m[1] + '</div></div>'
).join('');
const dups = (s.duplicates || []);
document.getElementById('warnings').innerHTML = dups.map(d =>
  '<div class="warn">\\u26A0\\uFE0F ' + (d.isNPlusOne ? 'N+1 detected' : 'Duplicate work') + ': ' +
  esc(d.sample) + ' ran ' + d.count + '\\u00D7 (' + d.totalDuration + 'ms total)</div>'
).join('');
const total = Math.max(R.totalDuration, 1);
document.getElementById('timeline').innerHTML = (R.steps || []).map((step, i) => {
  const left = (step.offset / total) * 100;
  const width = Math.max((step.duration / total) * 100, 0.5);
  return '<div class="tl-row"><div class="tl-label" title="' + esc(step.name) + '">' + esc(step.name) +
    (step.type ? ' [' + esc(step.type) + ']' : '') + '</div>' +
    '<div class="tl-bar-wrap"><div class="tl-bar c' + (i % 6) + (step.error ? ' err' : '') +
    '" style="left:' + left + '%;width:' + width + '%"></div></div>' +
    '<div class="tl-dur">' + step.duration + 'ms</div></div>';
}).join('') || '<div class="sub">No steps recorded</div>';
function esc(v){const d=document.createElement('div');d.textContent=String(v);return d.innerHTML;}
</script>
</body>
</html>`;
}

function escapeHtml(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

module.exports = { toShareableHtml };
